name: mlops
channels:
  - conda-forge
  - defaults
dependencies:
  - seaborn=0.11.2
  - pandas=1.3.5
  - pip=21.3.1
  - matplotlib=3.5.1
  - python=3.8
  - jupyterlab=3.2.1
  - scikit-learn=1.0.2
  - ipywidgets=7.6.5
  - jupyterlab_widgets=1.0.0
  - pip:
    - mlflow==1.14.1
    - wandb==0.12.20
    - protobuf==3.19.0
    - hydra-joblib-launcher==1.1.5
