name: check_data
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.3.5
  - pip=21.3.1
  - scipy=1.6.1
  - pip:
      - wandb==0.12.20
      - pytest==7.1.1
      - protobuf==3.19.0
      
